name: 'Test'
on:
  pull_request:
  workflow_dispatch:
# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-pr:
    name: 'Test PR'
    runs-on: [self-hosted, linux]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 'Fetch K tags'
        run: cd deps/k && git fetch origin 'refs/tags/*:refs/tags/*'
      - name: 'Set up Docker'
        run: |
          K_COMMIT="$(cd deps/k && git tag --points-at HEAD | cut --characters=2-)"
          echo "K_COMMIT=${K_COMMIT}"

          docker build --pull --file Dockerfile --tag dockerhub-runtimeverification.com/build/mir-semantics-ci:${K_COMMIT} --build-arg K_COMMIT="${K_COMMIT}" .
          
          docker run --name mir-semantics-ci --rm -it --detach --workdir /opt/workspace --user $(id -u):$(id -g) -v ${HOME}:${HOME} -v "$(pwd):/opt/workspace" -v "/etc/passwd:/etc/passwd:ro" -v "/etc/group:/etc/group:ro" dockerhub-runtimeverification.com/build/mir-semantics-ci:${K_COMMIT}
      - name: 'Build'
        run: docker exec mir-semantics-ci /bin/bash -c 'echo build'
      - name: 'Test'
        run: docker exec mir-semantics-ci /bin/bash -c 'echo test'
      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop mir-semantics-ci || true && docker rm mir-semantics-ci || true
